/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e5",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#00201c",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "secondary-container": "#86f2e4",
        "outline": "#76777d",
        "on-tertiary-fixed-variant": "#005047",
        "secondary-fixed-dim": "#6bd8cb",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#131b2e",
        "tertiary-fixed": "#62fae3",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#005049",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#00201d",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#89f5e7",
        "on-primary-container": "#7c839b",
        "on-surface-variant": "#45464d",
        "on-background": "#191c1e",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#009485",
        "on-error-container": "#93000a",
        "secondary": "#006a61",
        "inverse-primary": "#bec6e0",
        "surface": "#f7f9fb",
        "tertiary-container": "#00201c",
        "on-secondary-container": "#006f66",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#3cddc7",
        "on-primary-fixed": "#131b2e",
        "outline-variant": "#c6c6cd",
        "surface-tint": "#565e74"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "round-eight": "0.5rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
